<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>QuotesApi.Quotes.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\QuotesApi.Quotes.Application\QuotesApi.Quotes.Application.csproj" />
    <ProjectReference Include="..\..\..\QuotesApi.Persistence\QuotesApi.Persistence.csproj" />
    <ProjectReference Include="..\..\Jobs\QuotesApi.Jobs.Contracts\QuotesApi.Jobs.Contracts.csproj" />
    <ProjectReference Include="..\..\Messaging\QuotesApi.Messaging.Contracts\QuotesApi.Messaging.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" Version="10.9.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="QuotesApi.SharedKernel" />
    <Using Include="QuotesApi.Quotes.Domain" />
    <Using Include="QuotesApi.Quotes.Contracts" />
    <Using Include="QuotesApi.Quotes.Application" />
  </ItemGroup>

</Project>
