<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>QuotesApi.Identity.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\QuotesApi.Identity.Application\QuotesApi.Identity.Application.csproj" />
    <ProjectReference Include="..\..\..\QuotesApi.Persistence\QuotesApi.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="QuotesApi.SharedKernel" />
    <Using Include="QuotesApi.Identity.Domain" />
    <Using Include="QuotesApi.Identity.Contracts" />
    <Using Include="QuotesApi.Identity.Application" />
  </ItemGroup>

</Project>
