#!/usr/bin/env bash
#
# Brings up the Azure Service Bus emulator with the Day 19 topic and its two subscriptions.
#
#   ./scripts/start-emulator.sh          start and wait until healthy
#   ./scripts/start-emulator.sh --stop   tear down
#
# The emulator is Microsoft's own, so MaxDeliveryCount and the dead-letter queue behave
# exactly as they do in Azure. Only the connection string differs from production.

set -uo pipefail
export MSYS_NO_PATHCONV=1

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EMU_DIR="$SCRIPT_DIR/emulator"
COMPOSE="$EMU_DIR/docker-compose.yaml"
HEALTH_PORT="${EMULATOR_HTTP_PORT:-5300}"

winpath() { if command -v cygpath >/dev/null 2>&1; then cygpath -w "$1"; else printf '%s' "$1"; fi; }

if [ "${1:-}" = "--stop" ]; then
  docker compose -f "$(winpath "$COMPOSE")" --env-file "$(winpath "$EMU_DIR/.env")" down -v
  echo "Emulator stopped and its volumes removed."
  exit 0
fi

command -v docker >/dev/null || { echo "docker not found. Install Docker Desktop."; exit 1; }
docker info >/dev/null 2>&1 || {
  echo "The Docker daemon is not running. Start Docker Desktop and re-run."
  exit 1
}

# ---------------------------------------------------------------------------------------
# The .env is generated, never committed.
#
# It holds a SQL SA password, and while this one only ever guards a throwaway local
# container, a password in the repository is a password in the repository — the habit is what
# matters. Generated once and reused, so restarting the emulator does not invalidate the
# volume SQL Server has already initialised with the old one.
# ---------------------------------------------------------------------------------------
ENV_FILE="$EMU_DIR/.env"
if [ ! -f "$ENV_FILE" ]; then
  SA_PASSWORD="Sb$(node -e 'console.log(require("crypto").randomBytes(12).toString("base64url"))')Aa1!"
  cat > "$ENV_FILE" <<EOF
# Generated by start-emulator.sh. Not committed — see .gitignore.
CONFIG_PATH=$(winpath "$EMU_DIR/Config.json" | sed 's/\\/\\\\/g')
ACCEPT_EULA=Y
MSSQL_SA_PASSWORD=${SA_PASSWORD}
EMULATOR_HTTP_PORT=${HEALTH_PORT}
EOF
  echo "Generated $ENV_FILE"
fi

echo "Starting the emulator (first run pulls ~1.5GB of images)…"
docker compose -f "$(winpath "$COMPOSE")" --env-file "$(winpath "$ENV_FILE")" up -d || exit 1

# ---------------------------------------------------------------------------------------
# Wait for readiness, not for the container to exist.
#
# The emulator reports healthy only after SQL Server is up AND it has created the entities
# from Config.json. Publishing before that point fails with a "no such entity" error that
# reads like a configuration mistake rather than a race.
# ---------------------------------------------------------------------------------------
printf 'Waiting for the emulator to become healthy'
for _ in $(seq 1 90); do
  if curl -sf -o /dev/null "http://localhost:${HEALTH_PORT}/health" 2>/dev/null; then
    echo
    echo "Emulator ready."
    echo
    echo "  topic         : quote-events"
    echo "  subscriptions : audit, search-index  (MaxDeliveryCount 3)"
    echo
    echo "  export ServiceBus__ConnectionString='Endpoint=sb://localhost;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;'"
    echo
    exit 0
  fi
  printf '.'
  sleep 2
done

echo
echo "Emulator did not become healthy. Recent logs:"
docker logs day19-servicebus-emulator --tail 40 2>&1 | sed 's/^/    /'
exit 1
