using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using QuotesApi.Models;
using QuotesApi.Dtos;
using QuotesApi.Repositories;
using QuotesApi.Services;

namespace QuotesApi.Extensions;

public static class QuoteEndpointExtensions
{
    public static readonly ActivitySource ActivitySource = new ActivitySource("QuotesApi.Custom");

    public static void MapQuoteEndpoints(this WebApplication app)
    {
        var group = app.MapGroup("/api/quotes");

        // Day 21 — THE HOT READ.
        //
        // Every visitor loading the home page hits this, and it is the same query every time,
        // so it is the natural candidate for a cache. It now goes through IQuoteReader
        // (CachedQuoteReader) instead of straight to the repository.
        //
        // The response shape is unchanged: CachedQuote carries the same six fields the
        // repository's Quote does, so Day 16's isQuote() guard sees no difference between a
        // cached and an uncached response. A cache that changes the contract is not a cache,
        // it is a rewrite.
        group.MapGet("/", async (QuotesApi.Caching.IQuoteReader reader, CancellationToken ct) =>
            Results.Ok(await reader.GetAllAsync(ct)));

        group.MapGet("/{id:int}", async (int id, IQuoteRepository repo, CancellationToken ct) =>
            await repo.GetByIdAsync(id, ct) is Quote quote ? Results.Ok(quote) : Results.NotFound());

                group.MapPost("/", async (CreateQuoteRequest request, IQuoteRepository repo, IClock clock, ClaimsPrincipal user, ILogger<Program> logger, QuotesApi.Data.AppDbContext db, QuotesApi.Outbox.IOutboxWriter outbox, QuotesApi.Caching.IQuoteReader reader, CancellationToken ct) =>
        {
            var userIdClaim = user.FindFirst(ClaimTypes.NameIdentifier)?.Value ?? user.FindFirst("sub")?.Value;
            int.TryParse(userIdClaim, out var userId); 

                        logger.LogInformation("Attempting to create quote for user {UserId}", userId);
            
            using var activity = ActivitySource.StartActivity("compute-quote-creation");
            activity?.SetTag("user.id", userId);
            // System.Threading.Thread.Sleep(1500);

            var result = Quote.Create(request.Author, request.Text, clock.UtcNow, userId);
            if (!result.IsSuccess) 
            {
                logger.LogWarning("Failed to create quote for user {UserId}. Reason: {Reason}", userId, result.Error);
                return Results.BadRequest(result.Error);
            }
            
            // Same author, same words = a double post. A different author saying the same thing
            // is allowed through, so this is scoped to the author rather than to the text alone.
            if (await repo.ExistsForAuthorAsync(request.Author, request.Text, null, ct))
            {
                logger.LogWarning("Rejected duplicate quote from user {UserId}", userId);
                return Results.Conflict(new DomainError(
                    "This author has already posted that quote. The same words credited to a different author are fine."));
            }

            // -------------------------------------------------------------------------
            // Day 20 — the transactional outbox.
            //
            // Day 19 committed the quote and then published, as two operations with no
            // transaction across them. A crash in between left the quote existing and the
            // event never sent, permanently and undetectably. That is a dual write, and there
            // is exactly one thing you can make atomic with a database write: another database
            // write. So the event becomes a row in the same database, saved under the same
            // transaction, and a relay publishes it afterwards.
            //
            // The explicit transaction is needed because the quote's id is generated by the
            // database, so the outbox row cannot be staged until the insert has produced one.
            // Two SaveChanges calls, one transaction — both commit or neither does.
            // -------------------------------------------------------------------------
            await using var transaction = await db.Database.BeginTransactionAsync(ct);

            await repo.AddAsync(result.Value!, ct);   // SaveChanges #1, inside the transaction

            var messageId = outbox.Enqueue(
                type: QuotesApi.Messaging.QuoteEventTypes.Created,
                aggregateType: nameof(Quote),
                aggregateId: result.Value!.Id.ToString(),
                payload: new
                {
                    QuoteId = result.Value!.Id,
                    result.Value!.Author,
                    result.Value!.Text,
                    result.Value!.CreatedAt
                },
                occurredAt: result.Value!.CreatedAt);

            await db.SaveChangesAsync(ct);            // SaveChanges #2, same transaction
            await transaction.CommitAsync(ct);

            // Day 21: drop the cached list AFTER the commit, never before.
            //
            // Invalidating first opens a window in which a concurrent reader repopulates the
            // cache from the pre-commit state, and the stale value then survives for a full
            // expiration — a bug that only appears under concurrency and looks like the cache
            // "randomly" serving old data.
            await reader.InvalidateAsync(ct);

            // Past this line both rows are durable. Nothing is published yet, and that is the
            // point: publishing is now a separate, retryable step that cannot lose the event,
            // because the event is already written down.
            logger.LogInformation(
                "Created quote {QuoteId} for user {UserId} and staged outbox message {MessageId}.",
                result.Value!.Id, userId, messageId);

            return Results.Created($"/api/quotes/{result.Value!.Id}", result.Value);
        }).RequireAuthorization("can-edit-quotes");

        group.MapPut("/{id:int}/author", async (int id, UpdateAuthorRequest request, IQuoteRepository repo, QuotesApi.Caching.IQuoteReader reader, CancellationToken ct) =>
        {
            var quote = await repo.GetByIdAsync(id, ct);
            if (quote is null) return Results.NotFound();

            // Re-crediting a quote can walk it into a duplicate: if the new author already has
            // these exact words, saving would give them the same quote twice. `id` is excluded
            // so the row never collides with itself.
            if (await repo.ExistsForAuthorAsync(request.Author, quote.Text, id, ct))
            {
                return Results.Conflict(new DomainError(
                    "That author already has this quote. Credit it to someone else, or delete the existing one."));
            }

            // ChangeAuthor mutates the tracked entity, but nothing is persisted until
            // UpdateAsync runs — an early return here leaves the database untouched.
            var result = quote.ChangeAuthor(request.Author);
            if (!result.IsSuccess) return Results.BadRequest(result.Error);

            await repo.UpdateAsync(quote, ct);

            // The author is part of the cached list, so re-crediting a quote makes the cached
            // copy wrong. Every write path that changes what GET /api/quotes returns has to
            // invalidate — miss one and the cache is stale in a way only that one operation
            // triggers, which is the hardest kind of cache bug to find.
            await reader.InvalidateAsync(ct);

            return Results.NoContent();
        }).RequireAuthorization("can-edit-quotes");

        // DELETE applies the Custom Authorization Requirement Handler
        group.MapDelete("/{id:int}", async (int id, IQuoteRepository repo, IAuthorizationService authService, ClaimsPrincipal user, QuotesApi.Caching.IQuoteReader reader, CancellationToken ct) =>
        {
            var quote = await repo.GetByIdAsync(id, ct);
            if (quote is null) return Results.NotFound();

            var authResult = await authService.AuthorizeAsync(user, id, "IsQuoteOwner");
            if (!authResult.Succeeded)
            {
                return Results.Forbid(); // 403 if they don't own it
            }

            quote.Delete();
            await repo.UpdateAsync(quote, ct);

            // Same rule as the create path: the write is durable before the cache is dropped.
            await reader.InvalidateAsync(ct);

            return Results.NoContent();
        }).RequireAuthorization();
    }
}








