/**
 * Production configuration — swapped in by the `fileReplacements` entry in angular.json.
 *
 * The URL points at the BFF, not at the Quotes API. The browser is never given the API's
 * address, because the browser is never allowed to call it: the API rejects anything without
 * a managed-identity token in `X-Caller-Token`, and only the BFF can mint one.
 *
 * This is a public hostname, not a secret — which is the point. There is nothing in this
 * bundle worth extracting, because the credential that opens the API is minted server-side,
 * per request, by the platform.
 *
 * Regenerated by `scripts/set-bff-url.mjs` during deployment, so the value below is whatever
 * the last deploy resolved. Editing it by hand is fine; it will be overwritten next deploy.
 */
export const environment = {
  production: true,
  apiBaseUrl: 'https://quotes-bff.happydesert-51845d93.centralindia.azurecontainerapps.io/api',
} as const;
