<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>QuotesApi.Jobs.Contracts</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\QuotesApi.SharedKernel\QuotesApi.SharedKernel.csproj" />
    <ProjectReference Include="..\QuotesApi.Jobs.Domain\QuotesApi.Jobs.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="QuotesApi.SharedKernel" />
    <Using Include="QuotesApi.Jobs.Domain" />
  </ItemGroup>

</Project>
