// =================================================================================================
// Day 32 — the ship.
//
// Four applications and two databases: the Quotes stack as it stands after Day 27 (a modular
// monolith behind a token broker behind an Angular client) and the Dispatch capstone as it stands
// after Day 31. Everything built between Day 1 and Day 31 that can be deployed, deployed.
//
// Subscription-scoped, because three of the things this has to do cross a resource-group boundary:
//
//   * it creates its own resource group, so teardown is one `az group delete`;
//   * it grants AcrPull on a registry that lives in another group;
//   * it runs in a Container Apps environment that lives in a third.
//
// A template that only works inside a group somebody made by hand has an undocumented
// prerequisite. This one has none: given a subscription, it is complete.
// =================================================================================================

targetScope = 'subscription'

@description('Region. Everything else in this subscription is in centralindia; staying there keeps image pulls in-region and free.')
param location string = 'centralindia'

@description('Resource group this deployment owns outright. Deleting it deletes the ship and nothing else.')
param resourceGroupName string = 'rg-ship-day32'

// --- who administers SQL -------------------------------------------------------------------------

@description('Entra OBJECT id of the SQL administrator. Not a password — this server has none.')
param sqlAdminObjectId string

@description('Display name for that administrator, shown in the portal.')
param sqlAdminLogin string

@description('User or Group. The wrong value deploys cleanly and then refuses every login.')
@allowed([ 'User', 'Group' ])
param sqlAdminPrincipalType string = 'User'

// --- what we reuse rather than create -------------------------------------------------------------

@description('Container Apps environment to run in, as a resource id. Reused, never created. Azure permits ONE managed environment per region per subscription and this subscription has already spent its allowance on thinkschool-env; Day 24 found that out mid-deployment with MaxNumberOfRegionalEnvironmentsInSubExceeded. An environment is a shared boundary rather than a per-project resource, so reuse is the normal case.')
param managedEnvironmentId string

@description('DNS suffix of that environment. Needed up front because the frontend bundle bakes the broker URL in at BUILD time — see scripts/build-images.sh.')
param environmentDefaultDomain string

@description('Registry holding the four images. Reused: a second Basic registry is a second fixed monthly charge for no benefit.')
param containerRegistryName string

@description('Resource group of that registry. A separate parameter because the role assignment has to be scoped to it.')
param containerRegistryResourceGroup string

@description('Image tag to run. Pinned, never `latest` — see modules/apps.bicep.')
param imageTag string = 'day32'

// --- the one Entra app this reuses ----------------------------------------------------------------

@description('App ID URI of the Entra application that guards the Quotes API, reused from Day 17. The API refuses any request whose X-Caller-Token is not an app-only token for this audience carrying the Api.Invoke role. Granting that role to this deployment identity is an Entra operation rather than an ARM one, so it happens in scripts/grant-entra-role.sh.')
param quotesApiAppIdUri string

@description('Tenant the caller token must come from.')
param quotesApiTenantId string = subscription().tenantId

@description('App role the caller token must carry.')
param quotesApiRequiredRole string = 'Api.Invoke'

@description('Audience Dispatch requires. Created by scripts/setup-dispatch-entra.sh and read back by deploy.sh. Empty leaves Dispatch unauthenticated, which is never what a deployment wants.')
param dispatchAuthAudience string = ''

// --- secrets, passed in, never defaulted ----------------------------------------------------------

@description('Connection string of an EXISTING Application Insights component. Reused from Day 26 -- a second component would split the traces of one system across two places, which is worse than having none. Empty disables telemetry and the app still runs.')
param appInsightsConnectionString string = ''

@description('JWT signing key for the Quotes API. Generated by the deploy script, stored in Key Vault, never printed and never committed.')
@secure()
param jwtSigningKey string

@description('Name of the EXISTING Service Bus namespace carrying the quote-events topic. Reused from Day 26 -- a Standard namespace costs about Rs 28/day standing, and this one already has the topic and both subscriptions the API expects.')
param serviceBusNamespaceName string

@description('Resource group of that namespace. A separate parameter because the role assignments have to be scoped to it.')
param serviceBusResourceGroup string

param tags object = {
  day: '32'
  purpose: 'ship-demo-postmortem'
}

// -------------------------------------------------------------------------------------------------
// Names.
//
// Derived from uniqueString over the subscription and the group name, which depends on nothing that
// changes between runs. A teardown followed by a redeploy reproduces every name exactly — which
// matters because the demo transcript and the postmortem quote them.
// -------------------------------------------------------------------------------------------------
var suffix = uniqueString(subscription().subscriptionId, resourceGroupName)

var quotesApiName = 'ca-quotes-api'
var quotesBffName = 'ca-quotes-bff'
var quotesWebName = 'ca-quotes-web'
var dispatchApiName = 'ca-dispatch-api'

var quotesApiUrl = 'https://${quotesApiName}.${environmentDefaultDomain}'
var quotesBffUrl = 'https://${quotesBffName}.${environmentDefaultDomain}'
var quotesWebUrl = 'https://${quotesWebName}.${environmentDefaultDomain}'

resource rg 'Microsoft.Resources/resourceGroups@2024-03-01' = {
  name: resourceGroupName
  location: location
  tags: tags
}

// -------------------------------------------------------------------------------------------------
// One identity for all four applications.
//
// USER-assigned, where Day 17 used system-assigned, and that difference is what lets this deploy in
// a single pass. A system-assigned identity does not exist until its app exists — but the app
// cannot pull its image until that identity holds AcrPull, and it pulls during creation. The usual
// escape is to deploy a placeholder public image, grant the role, then redeploy for real.
// `ca-dispatch-api-dev` over in rg-dispatch-dev is still frozen on the placeholder half of exactly
// that dance, left there by Day 24.
//
// One identity rather than four is a real tradeoff and worth naming. Four would let the frontend
// hold nothing at all, the broker hold only the API role, and each API reach only its own database.
// One means any of the four could in principle do what any other can. At four co-deployed apps
// inside a single trust boundary that is an acceptable trade for a deployment somebody can hold in
// their head; the day any one of them is operated by a different person, it stops being acceptable.
// -------------------------------------------------------------------------------------------------
module identity 'modules/identity.bicep' = {
  name: 'identity'
  scope: rg
  params: {
    name: 'id-ship-${suffix}'
    location: location
    tags: tags
  }
}

module acrPull 'modules/acr-pull.bicep' = {
  name: 'acr-pull'
  scope: resourceGroup(containerRegistryResourceGroup)
  params: {
    containerRegistryName: containerRegistryName
    principalId: identity.outputs.principalId
  }
}

// -------------------------------------------------------------------------------------------------
// The one value that genuinely is a secret.
//
// Everything else in this template is a public identifier — tenant ids, client ids, hostnames — and
// is written in plain text on purpose. The JWT signing key is not: whoever holds it can mint a token
// for any user. It goes in Key Vault and the API references it; it is never an ARM output, never a
// plain environment value, never logged.
//
// There was briefly a second — a Service Bus SAS string — and removing it was the best change made
// to this template. See modules/servicebus-rbac.bicep.
// -------------------------------------------------------------------------------------------------
module vault 'modules/keyvault.bicep' = {
  name: 'vault'
  scope: rg
  params: {
    name: 'kv-ship-${suffix}'
    location: location
    readerPrincipalId: identity.outputs.principalId

    // The same person who administers SQL. Passed explicitly rather than reusing the SQL parameter
    // inside the module, because the two roles are unrelated and will diverge the day a deployment
    // identity stops being a human being.
    operatorPrincipalId: sqlAdminObjectId
    jwtSigningKey: jwtSigningKey
    tags: tags
  }
}

// Send and Receive on Day 26's namespace, in Day 26's resource group. The second cross-group grant
// in this template, and the second reason it is subscription-scoped.
module serviceBus 'modules/servicebus-rbac.bicep' = {
  name: 'servicebus-rbac'
  scope: resourceGroup(serviceBusResourceGroup)
  params: {
    namespaceName: serviceBusNamespaceName
    principalId: identity.outputs.principalId
  }
}

// The L2 behind HybridCache. Reached with a token, not a key — see the module for why that is
// worth a package reference and twenty lines of client code.
module redis 'modules/redis.bicep' = {
  name: 'redis'
  scope: rg
  params: {
    name: 'redis-ship-${suffix}'
    location: location
    principalId: identity.outputs.principalId
    principalName: identity.outputs.name
    tags: tags
  }
}

module sql 'modules/sql.bicep' = {
  name: 'sql'
  scope: rg
  params: {
    location: location
    serverName: 'sql-ship-${suffix}'
    databaseNames: [ 'quotes', 'dispatch' ]
    sqlAdminObjectId: sqlAdminObjectId
    sqlAdminLogin: sqlAdminLogin
    sqlAdminPrincipalType: sqlAdminPrincipalType
    tags: tags
  }
}

module apps 'modules/apps.bicep' = {
  name: 'apps'
  scope: rg
  params: {
    location: location
    managedEnvironmentId: managedEnvironmentId
    containerRegistryName: containerRegistryName
    imageTag: imageTag
    identityResourceId: identity.outputs.resourceId
    identityClientId: identity.outputs.clientId

    quotesApiName: quotesApiName
    quotesBffName: quotesBffName
    quotesWebName: quotesWebName
    dispatchApiName: dispatchApiName

    quotesApiUrl: quotesApiUrl
    quotesBffUrl: quotesBffUrl
    quotesWebUrl: quotesWebUrl

    quotesApiAppIdUri: quotesApiAppIdUri
    quotesApiTenantId: quotesApiTenantId
    quotesApiRequiredRole: quotesApiRequiredRole
    dispatchAuthTenantId: subscription().tenantId
    dispatchAuthAudience: dispatchAuthAudience

    sqlServerFqdn: sql.outputs.serverFqdn
    redisEndpoint: redis.outputs.endpoint
    appInsightsConnectionString: appInsightsConnectionString
    jwtSecretUri: vault.outputs.jwtSecretUri
    serviceBusFullyQualifiedNamespace: serviceBus.outputs.fullyQualifiedNamespace

    tags: tags
  }
  // Explicit: nothing in this module's parameters references acrPull, so Bicep would otherwise be
  // free to submit them in parallel and the very first image pull would be a 401. The Service Bus
  // grant is a real parameter dependency and needs no such help.
  dependsOn: [ acrPull ]
}

output resourceGroupName string = rg.name

output quotesWebUrl string = quotesWebUrl
output quotesBffUrl string = quotesBffUrl
output quotesApiUrl string = quotesApiUrl
output dispatchApiUrl string = 'https://${dispatchApiName}.${environmentDefaultDomain}'

output sqlServerName string = sql.outputs.serverName
output sqlServerFqdn string = sql.outputs.serverFqdn

@description('The CLIENT id. What SQL derives a user SID from, and what the connection strings carry. NOT the principal id — see modules/identity.bicep.')
output identityClientId string = identity.outputs.clientId

@description('The OBJECT id. What role assignments and Entra app-role grants name.')
output identityPrincipalId string = identity.outputs.principalId

output identityName string = identity.outputs.name
output vaultName string = vault.outputs.name
output redisHostName string = redis.outputs.hostName
