// <auto-generated />
using System;
using Dispatch.WorkManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dispatch.WorkManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WorkManagementDbContext))]
    partial class WorkManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("workmanagement")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dispatch.WorkManagement.Domain.WorkOrders.WorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedTechnicianId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DueBy")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Priority")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("RaisedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ReservationConfirmedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ReservationDeadline")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "DueBy")
                        .HasDatabaseName("IX_WorkOrders_Open_DueBy")
                        .HasFilter("[Status] IN ('Raised', 'Triaged', 'Scheduled', 'InProgress')");

                    b.ToTable("WorkOrders", "workmanagement");
                });

            modelBuilder.Entity("Dispatch.WorkManagement.Domain.WorkOrders.WorkOrder", b =>
                {
                    b.OwnsMany("Dispatch.WorkManagement.Domain.WorkOrders.LabourEntry", "Labour", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Minutes")
                                .HasColumnType("int");

                            b1.Property<string>("Note")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<Guid>("TechnicianId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("WorkOrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("WorkOrderId");

                            b1.ToTable("WorkOrderLabour", "workmanagement");

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderId");
                        });

                    b.OwnsOne("Dispatch.WorkManagement.Domain.WorkOrders.ScheduledWindow", "Window", b1 =>
                        {
                            b1.Property<Guid>("WorkOrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("End")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("WindowEnd");

                            b1.Property<DateTimeOffset>("Start")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("WindowStart");

                            b1.HasKey("WorkOrderId");

                            b1.ToTable("WorkOrders", "workmanagement");

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderId");
                        });

                    b.OwnsOne("Dispatch.WorkManagement.Domain.WorkOrders.ServiceAddress", "Address", b1 =>
                        {
                            b1.Property<Guid>("WorkOrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("AddressCity");

                            b1.Property<string>("Line")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("AddressLine");

                            b1.Property<string>("Postcode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("AddressPostcode");

                            b1.HasKey("WorkOrderId");

                            b1.ToTable("WorkOrders", "workmanagement");

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Labour");

                    b.Navigation("Window");
                });
#pragma warning restore 612, 618
        }
    }
}
