env:
  contexts:
  - excludePaths: []
    name: baseline
    urls:
    - https://ca-quotes-web.happydesert-51845d93.centralindia.azurecontainerapps.io
  parameters:
    failOnError: true
    progressToStdout: false
jobs:
- parameters:
    enableTags: false
    maxAlertsPerRule: 10
  type: passiveScan-config
- parameters:
    maxDuration: 2
    url: https://ca-quotes-web.happydesert-51845d93.centralindia.azurecontainerapps.io
  type: spider
- parameters:
    maxDuration: 5
  type: passiveScan-wait
- parameters:
    format: Long
    summaryFile: /home/zap/zap_out.json
  rules: []
  type: outputSummary
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: zap-quotes-web.html
    reportTitle: ZAP Scanning Report
    template: traditional-html
  type: report
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: zap-quotes-web.json
    reportTitle: ZAP Scanning Report
    template: traditional-json
  type: report
