// =============================================================================================
// Parameters for the identity deployment.
//
// The notable property of this file is what it does NOT contain: no password, no key, no
// connection string, and no `@secure()` parameter. Not because they are stored carefully
// elsewhere — because the design removed the need for them.
//
// Every value below is a public identifier. An object id, a client id and a login name are all
// things Entra will tell anyone who asks, and none of them grants access on its own. They are
// read from the environment rather than committed only because they are specific to one
// directory and one subscription, so a committed value would be wrong for everybody else.
// =============================================================================================

using './main.bicep'

param environmentName = 'dev'
param location = readEnvironmentVariable('LOCATION', 'centralindia')

// The Entra principal that administers SQL. Resolved by scripts/deploy.sh from the signed-in
// user, which is a compromise the script names out loud: production wants a GROUP here, because
// a group survives someone leaving the team and a named individual becomes an orphaned admin.
param sqlAdminObjectId = readEnvironmentVariable('SQL_ADMIN_OBJECT_ID', '00000000-0000-0000-0000-000000000000')
param sqlAdminLogin = readEnvironmentVariable('SQL_ADMIN_LOGIN', 'sql-identity-admin')

// The app registration that fronts the API. Created by scripts/entra-app.sh, because an app
// registration is a Microsoft Graph object and ARM cannot create one.
//
// A client id is designed to be public — it is embedded in browser JavaScript in every SPA that
// signs in with Entra. It is a plain parameter for that reason, and treating it as a secret
// would be the cargo-cult version of this exercise.
param entraClientId = readEnvironmentVariable('ENTRA_CLIENT_ID', '00000000-0000-0000-0000-000000000000')

// The NAME of the secret, never its value. The value is generated by the deploy script and
// written straight to the vault's data plane with `az keyvault secret set`, so it never passes
// through ARM, a parameter, or a deployment history entry.
param thirdPartySecretName = 'payments-webhook-signing-key'
